### ISSUE TITLE
Extra Argument In Call

### ISSUE THREAD

**Issue by IceFireCreations** [kean/Nuke-Toucan-Plugin#1]
Maybe because it is late but I am getting an extra argument in call error when using the plug in code - 

                request.process(key: "Avatar") {
                    return $0.resize(CGSize(width: 500, height: 500), fitMode: .crop)
                        .maskWithEllipse()
                }

**Comment by kean** [comment]
Hey, compiles just fine on my machine. Make sure that you are using Xcode with the most recent Command Line Tools.

**Comment by IceFireCreations** [comment]
Re-installed command line tools and all working. By the way a big thank you fo Nuke it just amazing.
