### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by sapsaldog** [kean/Nuke-Toucan-Plugin#2]
The readme file is already outdated.

I don't know how to use this library well.

Maybe I misconceived something, but I'm almost sure I didn't

**Comment by kean** [comment]
Hey! It seems that everything is up to date. The project uses Nuke 5.x (latest) and Toucan 0.6 (latest). Maybe there is something specific in readme which it no longer true? Could you please point it out to me?

**Comment by sapsaldog** [comment]
Hey! Thanks for replying. 

Maybe My setting isn't set properly.

What I found is in the blew screenshot.

It's the exact same code as described in readme (except the url)

Ofcourse I know what the key means, and I understand that It is possible to occur a error in runtime, but I can't understand the compile error.

I set the Podfile 

pod 'Nuke-Toucan-Plugin'
pod 'Toucan'

Please let me know how to handle this correctly if I was wrong in the way of making a code.


![2017-05-15_15-47-30](https://cloud.githubusercontent.com/assets/873280/26045592/eae8965c-3985-11e7-980e-dc062f221158.png)

**Comment by sapsaldog** [comment]
I found the error.

the missing point was "import NukeToucanPlugin"

I think the import option should be incorporated for the people who will have a confusion like me
